"""Remover coluna password_hash da tabela Membro

Revision ID: 1095404ac242
Revises: cria_usuarios_manual
Create Date: 2026-07-08 15:35:44.014869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1095404ac242'
down_revision = 'cria_usuarios_manual'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.drop_table('professor')
    with op.batch_alter_table('banca', schema=None) as batch_op:
        batch_op.alter_column('horario',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('responsavel_banca',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('orientador',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('nivel',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('drive_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pendente'::character varying"))
        batch_op.alter_column('site_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pendente'::character varying"))
        batch_op.drop_column('local')
        batch_op.drop_column('aluno')
        batch_op.drop_column('titulo')

    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('linha_de_pesquisa',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.alter_column('ano',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('EXTRACT(year FROM CURRENT_DATE)'))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               nullable=True)
        batch_op.alter_column('destinatario',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'usado'::character varying"))
        batch_op.create_unique_constraint('numero_ano_tipo_unico', ['numero', 'ano', 'tipo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.drop_constraint('numero_ano_tipo_unico', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'usado'::character varying"))
        batch_op.alter_column('destinatario',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('ano',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('EXTRACT(year FROM CURRENT_DATE)'))

    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('linha_de_pesquisa',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('banca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aluno', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('local', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.alter_column('site_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pendente'::character varying"))
        batch_op.alter_column('drive_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pendente'::character varying"))
        batch_op.alter_column('nivel',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('orientador',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('responsavel_banca',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('horario',
               existing_type=postgresql.TIME(),
               nullable=True)

    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('professor_pkey')),
    sa.UniqueConstraint('email', name=op.f('professor_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
