"""Adicionar coluna linha_de_pesquisa na tabela membro

Revision ID: 6c4539cda4d6
Revises: 7b58cceb4542
Create Date: 2026-04-24 17:16:51.490173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4539cda4d6'
down_revision = '7b58cceb4542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linha_de_pesquisa', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.drop_column('linha_de_pesquisa')

    # ### end Alembic commands ###
